# Generated by Django 5.2.1 on 2025-05-24 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricehistory_set', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaserequest_set', to='cars.car'),
        ),
    ]
