# Generated by Django 5.2.1 on 2025-05-08 15:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электрическая', 'Электрическая'), ('Гибрид', 'Гибрид'), ('Газ', 'Газ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Механическая', 'Механическая'), ('Автоматическая', 'Автоматическая'), ('Робот', 'Робот'), ('Вариатор', 'Вариатор')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1901), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='body_type',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Хетчбек', 'Хетчбек'), ('SUV', 'SUV'), ('Купе', 'Купе'), ('Кабриолет', 'Кабриолет'), ('Минивэн', 'Минивэн'), ('Пикап', 'Пикап')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='doors',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='drive_type',
            field=models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('4WD', '4WD'), ('AWD', 'AWD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='power',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='carspecification',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Принято', 'Принято'), ('Отклонено', 'Отклонено'), ('Завершено', 'Завершено')], default='В ожидании', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'car')},
        ),
        migrations.AlterModelTable(
            name='car',
            table='Cars',
        ),
        migrations.AlterModelTable(
            name='carspecification',
            table='CarSpecifications',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='Favorites',
        ),
        migrations.AlterModelTable(
            name='purchaserequest',
            table='PurchaseRequests',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('changed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.user')),
            ],
            options={
                'db_table': 'PriceHistory',
            },
        ),
    ]
