# Generated by Django 5.2.1 on 2025-05-19 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_user_block_reason_alter_favorite_car_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='chatrequest',
            table=None,
        ),
    ]
