# Generated by Django 5.2.1 on 2025-05-10 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_purchaserequest_final_price_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='main_photo_url',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_photos/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
