# Generated by Django 5.2.1 on 2025-05-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_main_photo_url_purchaserequest_photo_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='photo_file',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='photo_url',
        ),
    ]
