# Generated by Django 5.2.1 on 2025-05-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_purchaserequest_photo_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_new_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
