# Generated by Django 5.2.1 on 2025-05-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_user_has_new_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
