# Generated by Django 5.2.1 on 2025-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_purchaserequest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], default='used', max_length=20),
        ),
    ]
